apiVersion: v1
kind: Service
metadata:
  name: {{ include "local-demo.fullname" . }}
  annotations:
    zarf.dev/connect-description: "nginx webserver"
  labels:
    zarf.dev/connect-name: nginx
    {{- include "local-demo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "local-demo.selectorLabels" . | nindent 4 }}
